### ISSUE TITLE
Install instructions unclear

### ISSUE THREAD

**Issue by skube** [sergiokopplin/carmesim#1]
Nice theme. I have one comment :smiley: 

It's not that clear that you need to install both Dracula **and** Carmesim via Package Control.  I think it should be more straightforward:
- Install Dracula color _scheme_ 
- Install Carmesim _theme_
- Edit User Settings with the following:

```
"color_scheme": "Packages/Dracula Color Scheme/Dracula.tmTheme",
"theme": "Carmesim.sublime-theme"
```
- Restart Sublime

**Comment by sergiokopplin** [comment]
Thank you for the comment!
I'm updating now!

**Comment by sergiokopplin** [comment]
All done!

**Comment by sergiokopplin** [comment]
better instructions on readme

**Comment by skube** [comment]
:+1: Wow I'm a contributor now?! :smile:  thank you!
