### ISSUE TITLE
Scroll bar controls not visible

### ISSUE THREAD

**Issue by mgmeyers** [sergiokopplin/carmesim#2]
The scroll bar background and the scroll bar controls are the same color which makes the scroll bars difficult to use.

![selection_001](https://cloud.githubusercontent.com/assets/2694747/6307755/6260f9ba-b8f3-11e4-9b62-ce463b3f3635.png)

**Comment by sergiokopplin** [comment]
Are you using windows or something? Because i'm using mac and the bar colors are different than your

![screen shot 2015-02-20 at 11 00 09 pm](https://cloud.githubusercontent.com/assets/2743180/6312046/404d96ce-b954-11e4-9d52-79a3bffbba6b.png)

**Comment by sergiokopplin** [comment]
Fixed by @mgmeyers on https://github.com/sergiokopplin/carmesim/pull/3, closed!
