### ISSUE TITLE
Bug: Close tab buttons appear as boxes prior to hover

### ISSUE THREAD

**Issue by AaronO** [sergiokopplin/carmesim#4]
![screen shot 2015-03-24 at 1 32 26 pm](https://cloud.githubusercontent.com/assets/949223/6801696/757b131e-d22a-11e4-88fd-16d0d5b691e6.png)

**Comment by sergiokopplin** [comment]
this error began happen to me, but i'm using the last version.
It is working for you now?
I did a clean install of the sublime and stopped working
